### PR TITLE
Initial DaskRunner for Beam.

### PR DESCRIPTION
**Pull request by alxmrs**
Here, I've created a minimum viable Apache Beam runner for Dask. My approach is to visit a Beam Pipeline an translate PCollections into Dask Bags, and PTransformations to Bag methods. 

In this version, I have supported enough operations to make test pipeline asserts work. The test themselves are not comprehensive. Further, there are [many Bag operations](https://docs.dask.org/en/latest/bag-api.html) that could be translated for greater efficiency. 

CC:  @pabloem

Fixes: #18962

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by cisaacstern** [comment]
> There's some ambiguity on how we can connect Dask to the runner. One of two options are:
> - To create a full Bag graph up front, then call compute.

This is what the `DirectRunner` appears to do. AFAICT, it:

1. [Instantiates a visitor](https://github.com/apache/beam/blob/48bad7d966a583055669850eb9fb558782f636a8/sdks/python/apache_beam/runners/direct/direct_runner.py#L532-L533) which is passed into `pipeline.visit` 
2. The [`visit_transform`](https://github.com/apache/beam/blob/48bad7d966a583055669850eb9fb558782f636a8/sdks/python/apache_beam/runners/direct/consumer_tracking_pipeline_visitor.py#L60) method of the visitor adds items to a few different iterable attributes of `self`
3. Those iterables are then passed to the executor in a few places [here](https://github.com/apache/beam/blob/48bad7d966a583055669850eb9fb558782f636a8/sdks/python/apache_beam/runners/direct/direct_runner.py#L535-L555)


> - To create pseudo graph structures, and evaluate as we traverse the graph.

I don't fully grok what is meant by "pseudo graph structure" here, but the `RayRunner` evaluates during its visitation cycle:

1. The visitor and executor are [collapsed into a single object](https://github.com/ray-project/ray_beam_runner/blob/45cf717a236143790dcfd9f5c1774f948cbe863d/ray_beam_runner/ray_runner.py#L70-L72)
2. The [hybrid visitor/executor's `visit_transform` method](https://github.com/ray-project/ray_beam_runner/blob/45cf717a236143790dcfd9f5c1774f948cbe863d/ray_beam_runner/translator.py#L428-L429) executes during visitation, using a [`translations` dict](https://github.com/ray-project/ray_beam_runner/blob/45cf717a236143790dcfd9f5c1774f948cbe863d/ray_beam_runner/translator.py#L400-L412) to map beam operations onto their ray equivalents

It looks like https://github.com/alxmrs/beam/pull/1/commits/7cbf5fa6ee5173627bacaa629e606076fdb318c3 lays a foundation for following the `RayRunner` approach, which makes sense to me!

cc @rabernat

**Comment by cisaacstern** [comment]
Also just thought I'd link the original meeting notes here, so we have all relevant documents in once place:

> https://docs.google.com/document/d/1Awj_eNmH-WRSte3bKcCcUlQDiZ5mMKmCO_xV-mHWAak/edit#

**Comment by alxmrs** [comment]
Hey @cisaacstern! Check this out now -- I've made some good progress today. The beam pipeline doesn't return the proper thing, but after inspecting it in the debugger, it does seem to pass Beam/python operations to Dask Bag executors.

**Comment by cisaacstern** [comment]
Awesome, @alxmrs! I should have a moment to take a closer look at this later this week.

**Comment by cisaacstern** [comment]
Despite best intentions, scarcity of time (and catching covid right before my last comment here!) meant that I wasn't able to review this. Hopefully I can help with getting the testing up and running, as outlined in https://github.com/pangeo-forge/pangeo-forge-recipes/issues/256#issuecomment-1182069939. Thanks for all the effort on this!

**Pull request closed without merging**
